import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'

test('private attendance transactions, snapshots, QR gates and correction conflicts', async () => {
 const db = new PGlite()
 await db.exec('create role anon; create role authenticated; create role service_role;')
 await db.exec((await Promise.all(['20260912163507_attendance_private.sql','20260912210000_attendance_email_code_auth.sql'].map(name=>readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8')))).join('\n'))
 const api=async(resource,action,body={},actor='teacher@example.com',instructor=true)=> (await db.query('select attendance_api($1,$2,$3,$4,$5,$6) as data',[actor,'google-sub',instructor,resource,action,JSON.stringify(body)])).rows[0].data
 const location=()=>({latitude:37,longitude:-122,accuracy:5,timestamp:Date.now()})
 await assert.rejects(api('unknown','list'),/Unknown attendance/)
 await assert.rejects(api('classes','destroy'),/Unknown attendance/)
 const { class:c }=await api('classes','create',{name:'Hip Hop',college:'College',term:'Fall',year:2026,start_date:'2020-01-01',end_date:'2030-01-01',timezone:'America/Los_Angeles',days:[1],start_time:'10:00',end_time:'11:00'})
 const {enrollments}=await api('enrollments','import',{classId:c.id,rows:[{name:'Student',email:' STUDENT@example.com ',college_id:'001'},{name:'Absent',college_id:'002'}]})
 assert.equal((await api('classes','list',{},'stranger@example.com',false)).classes.length,0)
 assert.equal((await api('classes','list',{},'student@example.com',false)).classes.length,1)
 await assert.rejects(api('enrollments','list',{classId:c.id},'student@example.com',false),/Instructor/)
 await assert.rejects(api('meetings','open',{classId:c.id,location:{...location(),accuracy:51}}),/fresh location/)
 const {meeting}=await api('meetings','open',{classId:c.id,location:location()})
 await assert.rejects(api('meetings','list',{classId:crypto.randomUUID(),meetingId:meeting.id}),/does not belong/)
 await assert.rejects(api('meetings','open',{classId:c.id,location:location()}),/End the open meeting/)
 await assert.rejects(api('enrollments','import',{classId:c.id,rows:[{name:'Duplicate',email:'student@example.com'}]}),/overlapping/)
 await assert.rejects(api('meetings','token',{meetingId:meeting.id}),/fresh location/)
 let {token,expiresAt}=await api('meetings','token',{meetingId:meeting.id,location:location()})
 assert.notEqual((await db.query('select token from attendance_meetings where id=$1',[meeting.id])).rows[0].token,token)
 const tokenSlot=(await db.query('select token_slot from attendance_meetings where id=$1',[meeting.id])).rows[0].token_slot
 assert.equal(Date.parse(expiresAt),(Number(tokenSlot)+1)*60_000)
 await db.query("update attendance_meetings set location_timestamp=clock_timestamp()-interval '61 seconds' where id=$1",[meeting.id])
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/instructor must refresh/)
 ;({token}=await api('meetings','token',{meetingId:meeting.id,location:location()}))
 await api('classes','update',{classId:c.id,archived:true})
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/archived/)
 await api('classes','update',{classId:c.id,archived:false})
 await db.query('update attendance_meetings set token_slot=token_slot-1 where id=$1',[meeting.id])
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/expired/)
 await db.query('update attendance_meetings set token_slot=floor(extract(epoch from clock_timestamp())/60)::bigint where id=$1',[meeting.id])
 assert.equal((await api('check-in','check_in',{token,location:{...location(),latitude:38}},'student@example.com',false)).error,'You must be within 50 meters of your instructor.')
 assert.match((await api('check-in','check_in',{token,location:{...location(),timestamp:1}},'student@example.com',false)).error,/stale/)
 const check=await api('check-in','check_in',{token,location:location()},'student@example.com',false)
 assert.equal(check.record.status,'present')
 const again=await api('check-in','check_in',{token,location:location()},'student@example.com',false)
 assert.equal(again.record.revision,1)
 const differentSub=(await db.query('select attendance_api($1,$2,$3,$4,$5,$6) as data',['student@example.com','different-google-sub',false,'check-in','check_in',JSON.stringify({token,location:location()})])).rows[0].data
 assert.match(differentSub.error,/another Google account/)
 const student=enrollments.find(e=>e.email)
 await db.query("update attendance_enrollments set effective_from=current_date-3,effective_to=current_date-2 where id=$1",[student.id])
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/actively enrolled/)
 await db.query('update attendance_enrollments set effective_to=null where id=$1',[student.id])
 await api('enrollments','update',{classId:c.id,enrollmentId:student.id,email:'corrected@example.com'})
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/actively enrolled/)
 assert.equal((await api('history','list',{},'student@example.com',false)).records.length,0)
 assert.equal((await api('check-in','check_in',{token,location:location()},'corrected@example.com',false)).record.status,'present')
 await api('enrollments','update',{classId:c.id,enrollmentId:student.id,email:'student@example.com'})
 const op={operationId:crypto.randomUUID(),meetingId:meeting.id,enrollmentId:student.id,status:'absent',expectedRevision:1,note:'Instructor correction'}
 assert.equal((await api('corrections','save',op)).record.revision,2)
 assert.equal((await api('corrections','save',op)).duplicate,true)
 assert.equal((await api('corrections','save',{...op,operationId:crypto.randomUUID()})).code,'conflict')
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/instructor/)
 await api('enrollments','update',{classId:c.id,enrollmentId:student.id,name:'Changed Name'})
 await api('meetings','extend',{meetingId:meeting.id})
 await assert.rejects(api('meetings','extend',{meetingId:meeting.id}),/cannot be extended/)
 const closed=await api('meetings','close',{meetingId:meeting.id})
 assert.equal(closed.records.length,2)
 assert.equal(closed.roster.find(r=>r.enrollment_id===student.id).name,'Student')
 assert.equal(closed.corrections.length,1)
 assert.ok(closed.failures.length>0)
 assert.equal((await db.query('select attendance_claim_failure_notice($1) as owner',[closed.failures[0].id])).rows[0].owner,'teacher@example.com')
 assert.equal((await db.query('select attendance_claim_failure_notice($1) as owner',[closed.failures[0].id])).rows[0].owner,null)
 assert.equal((await db.query('select latitude from attendance_meetings where id=$1',[meeting.id])).rows[0].latitude,null)
 const offline=await api('sync','save',{operations:[{...op,operationId:crypto.randomUUID(),expectedRevision:1},{...op,operationId:crypto.randomUUID(),expectedRevision:2,status:'present',note:'Reviewed offline edit'}]})
 assert.equal(offline.results[0].code,'conflict')
 assert.equal(offline.results[1].record.status,'present')
 const optionalNote={operationId:crypto.randomUUID(),meetingId:meeting.id,enrollmentId:student.id,status:'present',expectedRevision:3,recordedAt:new Date().toISOString()}
 await assert.rejects(api('corrections','save',{...optionalNote,recordedAt:'2099-01-01T00:00:00Z'}),/timeline/)
 assert.equal((await api('corrections','save',optionalNote)).saved,true)
 const makeup=await api('meetings','open',{classId:c.id,location:location()})
 assert.notEqual(makeup.meeting.id,meeting.id)
 await api('meetings','close',{meetingId:makeup.meeting.id})
 assert.equal((await api('meetings','cancel',{meetingId:makeup.meeting.id,note:'Meeting canceled'})).meeting.status,'cancelled')
 assert.match((await api('check-in','check_in',{token,location:location()},'student@example.com',false)).error,/expired/)
 assert.equal((await api('history','list',{},'student@example.com',false)).records.length,1)
 assert.equal((await api('history','list',{classId:crypto.randomUUID()},'student@example.com',false)).records.length,0)
 assert.equal((await api('history','list',{classId:c.id},'student@example.com',false)).records.length,1)
 assert.equal((await api('history','list',{},'stranger@example.com',false)).records.length,0)
 const mixed=await api('sync','save',{operations:[{...optionalNote,operationId:crypto.randomUUID(),meetingId:makeup.meeting.id},{...optionalNote,operationId:crypto.randomUUID(),expectedRevision:4}]});assert.ok(mixed.results[0].error);assert.equal(mixed.results[1].saved,true)
 await assert.rejects(db.exec('update attendance_corrections set note=\'tamper\''),/immutable/)
 await db.exec('set role anon')
 await assert.rejects(db.exec('select * from attendance_records'),/permission denied/)
 await assert.rejects(api('classes','list'),/permission denied/)
 await db.close()
})
